---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-prometheus-demo
  labels:
    app: spring-prometheus-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-prometheus-demo
  template:
    metadata:
      labels:
        app: spring-prometheus-demo
        type: spring-keda-testing
    spec:
      containers:
      - name: spring-prometheus-demo-app
        image: brianmmcclain/spring-prometheus-demo:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: spring-prometheus-demo
  labels:
    app: spring-prometheus-demo
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    type: spring-keda-testing
  ports:
    - protocol: TCP
      name: http-traffic
      port: 8080
      targetPort: 8080

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  
  name: spring-prometheus-demo-service-monitor
spec:
  selector:
    matchLabels:
      app: spring-prometheus-demo
  endpoints:
  - port: http-traffic
    path: '/actuator/prometheus'
    interval: 10s    